backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "portfolio_settings"
    label: "My Portfolio"
    files:
      - label: "Auto Gallery"
        name: "gallery"
        file: "projects.json"
        fields:
          - label: "Upload Content"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Select Photo/Video File (Optional)", name: "image", widget: "image", required: false}
              - {label: "YouTube Video Link (Optional)", name: "yt_link", widget: "string", required: false}
              - {label: "Short Description", name: "desc", widget: "text"}
